openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /hello-world:
    get:
      operationId: HelloWorld
      parameters:
        - name: Authorization
          description: Authorization header.
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
